extern _multiboot, _code, _bss, physical_end, loader

MULTIBOOT_VESA_MODE     equ 0
MULTIBOOT_VESA_WIDTH    equ 800
MULTIBOOT_VESA_HEIGHT   equ 600
MULTIBOOT_VESA_DEPTH    equ 32
MULTIBOOT_PAGE_ALIGN	equ 0x00000001
MULTIBOOT_MEMORY_INFO	equ 0x00000002
MULTIBOOT_VIDEO_MODE    equ 0x00000004
MULTIBOOT_AOUT_KLUDGE	equ 0x00010000
MULTIBOOT_HEADER_MAGIC	equ 0x1BADB002
MULTIBOOT_HEADER_FLAGS	equ MULTIBOOT_PAGE_ALIGN  | MULTIBOOT_MEMORY_INFO | MULTIBOOT_AOUT_KLUDGE  ;| MULTIBOOT_VIDEO_MODE
MULTIBOOT_CHECKSUM	    equ -(MULTIBOOT_HEADER_MAGIC + MULTIBOOT_HEADER_FLAGS)

section .multiboot
align 4
    ; Actual multiboot header goes here :)
    dd MULTIBOOT_HEADER_MAGIC
    dd MULTIBOOT_HEADER_FLAGS
    dd MULTIBOOT_CHECKSUM

    ; AOUT kludge
    dd _multiboot
    dd _code
    dd _bss
    dd physical_end
    dd loader

    ; Not enabling VESA for now.
    ; dd MULTIBOOT_VESA_MODE
    ; dd MULTIBOOT_VESA_WIDTH, MULTIBOOT_VESA_HEIGHT, MULTIBOOT_VESA_DEPTH
