MULTIBOOT_VESA_MODE     equ 0
MULTIBOOT_VESA_WIDTH    equ 800
MULTIBOOT_VESA_HEIGHT   equ 600
MULTIBOOT_VESA_DEPTH    equ 32

MULTIBOOT_PAGE_ALIGN	equ 1<<0
MULTIBOOT_MEMORY_INFO	equ 1<<1
MULTIBOOT_VIDEO_MODE    equ 1<<2
MULTIBOOT_AOUT_KLUDGE	equ 1<<16
MULTIBOOT_HEADER_MAGIC	equ 0x1BADB002
MULTIBOOT_HEADER_FLAGS	equ MULTIBOOT_PAGE_ALIGN  | MULTIBOOT_MEMORY_INFO ;| MULTIBOOT_AOUT_KLUDGE  ;| MULTIBOOT_VIDEO_MODE
MULTIBOOT_CHECKSUM	    equ -(MULTIBOOT_HEADER_MAGIC + MULTIBOOT_HEADER_FLAGS)

section .multiboot
align 4
    ; Actual multiboot header goes here :)
    dd MULTIBOOT_HEADER_MAGIC
    dd MULTIBOOT_HEADER_FLAGS
    dd MULTIBOOT_CHECKSUM
    ; dd 0, 0, 0, 0

    ; Not enabling VESA for now.
    ; dd MULTIBOOT_VESA_MODE
    ; dd MULTIBOOT_VESA_WIDTH, MULTIBOOT_VESA_HEIGHT, MULTIBOOT_VESA_DEPTH
